# Generated by Django 4.0.6 on 2022-07-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('query', models.CharField(max_length=500)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_on'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Accessories', 'Accessories'), ('Laptop', 'Laptop')], max_length=50),
        ),
    ]
