# Generated by Django 3.2.10 on 2022-07-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Printer', 'Printer'), ('Accessories', 'Accessories'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=50),
        ),
    ]
