# Generated by Django 4.0.6 on 2022-07-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default='aryan', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Desktop', 'Desktop'), ('Printer', 'Printer')], max_length=50),
        ),
    ]
