# Generated by Django 4.0.6 on 2022-07-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Printer', 'Printer'), ('Desktop', 'Desktop')], max_length=50),
        ),
    ]
