# Generated by Django 4.0.6 on 2022-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Printer', 'Printer'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Desktop', 'Desktop')], max_length=50),
        ),
    ]
