# Generated by Django 4.0.6 on 2022-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories')], max_length=50),
        ),
    ]
