# Generated by Django 4.0.6 on 2022-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Printer', 'Printer'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop')], max_length=50),
        ),
    ]
